# Generated by Django 2.2.3 on 2019-07-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='nama_file_image',
            field=models.CharField(default='profpic', max_length=255),
        ),
    ]
