# Generated by Django 2.2.3 on 2019-07-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0002_mentor_nama_file_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tanggal_dipost', models.DateField()),
                ('komen', models.IntegerField()),
                ('isi', models.TextField()),
                ('nama_file_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('quote', models.TextField()),
                ('nama_file_image', models.CharField(max_length=255)),
            ],
        ),
    ]
